require('plugins_conf.telecope')
require('plugins_conf.netrw')
require('plugins_conf.treesitter')
require('plugins_conf.lps')
require('plugins_conf.luaSnip')
require('plugins_conf.symbols-outline')
-- require('plugins_conf.lspSaga')
-- require('plugins_conf.rust_tools')
